title: Particles, Colors, Music.
email: team@cipherprime.com
description: >- # this means to ignore newlines until "baseurl:"
  <a href="https://cipherprime.com">Cipher Prime</a> makes games in Philly.
baseurl: /
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cipherprime
github_username:  cipherprime
external_url: "https://blog.cipherprime.com/"

# Jekyll settings
permalink: /:title/
paginate: 10

# Page settings
show_excerpts: true
post_footer: true

meta_description: The blog of Cipher Prime Studios in Philadelphia

# Theme settings
# dark_theme: false
# dark_header: true

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minimal-mistakes-jekyll
# remote_theme: niklasbuschmann/contrast
# redcarpet:
#     extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - classifier-reborn
